/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperRouteImport } from './routes/super'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MemberRouteImport } from './routes/member'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperProfileRouteImport } from './routes/super.profile'
import { Route as SuperMembersRouteImport } from './routes/super.members'
import { Route as MemberQrRouteImport } from './routes/member.qr'
import { Route as MemberProfileRouteImport } from './routes/member.profile'
import { Route as MemberAlertsRouteImport } from './routes/member.alerts'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminCommsRouteImport } from './routes/admin.comms'

const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperProfileRoute = SuperProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SuperRoute,
} as any)
const SuperMembersRoute = SuperMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => SuperRoute,
} as any)
const MemberQrRoute = MemberQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberAlertsRoute = MemberAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => MemberRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommsRoute = AdminCommsRouteImport.update({
  id: '/comms',
  path: '/comms',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/member': typeof MemberRouteWithChildren
  '/register': typeof RegisterRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/comms': typeof AdminCommsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/member/alerts': typeof MemberAlertsRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/qr': typeof MemberQrRoute
  '/super/members': typeof SuperMembersRoute
  '/super/profile': typeof SuperProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/admin/comms': typeof AdminCommsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/member/alerts': typeof MemberAlertsRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/qr': typeof MemberQrRoute
  '/super/members': typeof SuperMembersRoute
  '/super/profile': typeof SuperProfileRoute
  '/admin': typeof AdminIndexRoute
  '/member': typeof MemberIndexRoute
  '/super': typeof SuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/member': typeof MemberRouteWithChildren
  '/register': typeof RegisterRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/comms': typeof AdminCommsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/member/alerts': typeof MemberAlertsRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/qr': typeof MemberQrRoute
  '/super/members': typeof SuperMembersRoute
  '/super/profile': typeof SuperProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/member'
    | '/register'
    | '/super'
    | '/admin/comms'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/profile'
    | '/member/alerts'
    | '/member/profile'
    | '/member/qr'
    | '/super/members'
    | '/super/profile'
    | '/admin/'
    | '/member/'
    | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/admin/comms'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/profile'
    | '/member/alerts'
    | '/member/profile'
    | '/member/qr'
    | '/super/members'
    | '/super/profile'
    | '/admin'
    | '/member'
    | '/super'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/member'
    | '/register'
    | '/super'
    | '/admin/comms'
    | '/admin/logs'
    | '/admin/members'
    | '/admin/profile'
    | '/member/alerts'
    | '/member/profile'
    | '/member/qr'
    | '/super/members'
    | '/super/profile'
    | '/admin/'
    | '/member/'
    | '/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MemberRoute: typeof MemberRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SuperRoute: typeof SuperRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super/profile': {
      id: '/super/profile'
      path: '/profile'
      fullPath: '/super/profile'
      preLoaderRoute: typeof SuperProfileRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/members': {
      id: '/super/members'
      path: '/members'
      fullPath: '/super/members'
      preLoaderRoute: typeof SuperMembersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/member/qr': {
      id: '/member/qr'
      path: '/qr'
      fullPath: '/member/qr'
      preLoaderRoute: typeof MemberQrRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/alerts': {
      id: '/member/alerts'
      path: '/alerts'
      fullPath: '/member/alerts'
      preLoaderRoute: typeof MemberAlertsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comms': {
      id: '/admin/comms'
      path: '/comms'
      fullPath: '/admin/comms'
      preLoaderRoute: typeof AdminCommsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCommsRoute: typeof AdminCommsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommsRoute: AdminCommsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MemberRouteChildren {
  MemberAlertsRoute: typeof MemberAlertsRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberQrRoute: typeof MemberQrRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberAlertsRoute: MemberAlertsRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberQrRoute: MemberQrRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface SuperRouteChildren {
  SuperMembersRoute: typeof SuperMembersRoute
  SuperProfileRoute: typeof SuperProfileRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperMembersRoute: SuperMembersRoute,
  SuperProfileRoute: SuperProfileRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MemberRoute: MemberRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SuperRoute: SuperRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
