/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/comms`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/logs`; params?: Router.UnknownInputParams; } | { pathname: `/admin/members`; params?: Router.UnknownInputParams; } | { pathname: `/admin/profile`; params?: Router.UnknownInputParams; } | { pathname: `/member/alerts`; params?: Router.UnknownInputParams; } | { pathname: `/member`; params?: Router.UnknownInputParams; } | { pathname: `/member/profile`; params?: Router.UnknownInputParams; } | { pathname: `/member/qr`; params?: Router.UnknownInputParams; } | { pathname: `/super`; params?: Router.UnknownInputParams; } | { pathname: `/super/members`; params?: Router.UnknownInputParams; } | { pathname: `/super/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/comms`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/logs`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/members`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/member/alerts`; params?: Router.UnknownOutputParams; } | { pathname: `/member`; params?: Router.UnknownOutputParams; } | { pathname: `/member/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/member/qr`; params?: Router.UnknownOutputParams; } | { pathname: `/super`; params?: Router.UnknownOutputParams; } | { pathname: `/super/members`; params?: Router.UnknownOutputParams; } | { pathname: `/super/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/comms${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/admin/logs${`?${string}` | `#${string}` | ''}` | `/admin/members${`?${string}` | `#${string}` | ''}` | `/admin/profile${`?${string}` | `#${string}` | ''}` | `/member/alerts${`?${string}` | `#${string}` | ''}` | `/member${`?${string}` | `#${string}` | ''}` | `/member/profile${`?${string}` | `#${string}` | ''}` | `/member/qr${`?${string}` | `#${string}` | ''}` | `/super${`?${string}` | `#${string}` | ''}` | `/super/members${`?${string}` | `#${string}` | ''}` | `/super/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/comms`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/logs`; params?: Router.UnknownInputParams; } | { pathname: `/admin/members`; params?: Router.UnknownInputParams; } | { pathname: `/admin/profile`; params?: Router.UnknownInputParams; } | { pathname: `/member/alerts`; params?: Router.UnknownInputParams; } | { pathname: `/member`; params?: Router.UnknownInputParams; } | { pathname: `/member/profile`; params?: Router.UnknownInputParams; } | { pathname: `/member/qr`; params?: Router.UnknownInputParams; } | { pathname: `/super`; params?: Router.UnknownInputParams; } | { pathname: `/super/members`; params?: Router.UnknownInputParams; } | { pathname: `/super/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
